name: Worldsbestanticheatnocapfreetwentytwentyonetwothreeletsgoboisvapevefourfreeepog
version: '${project.version}'
main: gg.vape.Worldsbestanticheatnocapfreetwentytwentyonetwothreeletsgoboisvapevefourfreeepog
